name: Build PySnake with Pygbag
on:
  push:
    branches:
      - master
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build-pygbag:
    name: PySnake by PB
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checkout
      run: |
            echo "Attempting to install pygbag"
            python -m pip install pygbag
            echo "Successfully installed pygbag"
            echo "Attempting to build the game"
            python -m pygbag --build $GITHUB_WORKSPACE/main.py
            echo "Successfully build the game and complied to WebAssembly"

    - name : "Upload to GitHub pages branch gh-pages"
      uses: JamesIves/github-pages-deploy-action@4
      with:
        folder: ./build/web
